name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r app/requirements.txt

    - name: Run tests
      run: pytest app/tests/

    - name: Lint code
      run: pip install flake8 && flake8 app/

    - name: Build Docker image
      run: docker build -t demo-app .
