name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install flake8 pytest-cov bandit safety

    - name: Run linting
      run: flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run security scan
      run: |
        bandit -r app/ -c pyproject.toml || true
        safety check -r app/requirements.txt || true

    - name: Run tests with coverage
      run: pytest app/tests/ --cov=app --cov-report=xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

    - name: Build Docker image
      run: docker build -t demo-app .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'demo-app'
        format: 'table'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'
